algoritmo "aluguel de veiculo"
var
   km,dias,valor:real
inicio
      escreva ("Por quantos dias o carro foi alugado ? ")
      leia (dias)
      escreva ("Quantos kilometros o carro andou ? ")
      leia (km)
      valor <- (dias*90.00)+(km*0.20)
            escreval ("O valor total a pagar é de ",valor)
            escreva  ("Muito obrigado por ter alugado nosso veículo !")
            
fimalgoritmo
