algoritmo "semnome"
var
   I, f, p:inteiro
inicio
      escreva ("Digite o inicio da contagem : ")
      leia (I)
      escreva ("Digite o final da contagem : ")
      leia (F)
      escreva ("Contar de quantos em quantos : ")
      leia (p)
      se I < F entao
      enquanto I <= F faca
               escreva (I)
               I <- I + P
      fimenquanto
      senao
           enquanto I >= F faca
           escreva (I)
           I <- I -P
           fimenquanto
      fimse
fimalgoritmo
