algoritmo "semnome"
var

inicio
procedimento borda1
inicio
escreval ("+-------=======------+")
fimprocedimento
procedimento borda2
inicio
escreval ("~~~~~~~~:::::::~~~~~~~")
fimprocedimento
               escreval ("chamando o procedimento borda 1 borda 2 ")
               borda1
               escreval (" Inicio do programa    ")
               borda1
               borda2
               escreval (" Final do programa  ")
               borda2
               
fimalgoritmo
